// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0VlbCBzqg976QDq-vpoh3YmzTOro-guU',
    appId: '1:132422513872:web:ceb4a5feff43210f419ad5',
    messagingSenderId: '132422513872',
    projectId: 'compactmeter-1ec77',
    authDomain: 'compactmeter-1ec77.firebaseapp.com',
    storageBucket: 'compactmeter-1ec77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRE3FS5tmVahGpCyv8kYiPt813JPhNFpQ',
    appId: '1:132422513872:android:f087c686b9c0f5f2419ad5',
    messagingSenderId: '132422513872',
    projectId: 'compactmeter-1ec77',
    storageBucket: 'compactmeter-1ec77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA24oWqCR85FObPInV-bcDEhEWDV7J1e80',
    appId: '1:132422513872:ios:dfe8804d53faaf6a419ad5',
    messagingSenderId: '132422513872',
    projectId: 'compactmeter-1ec77',
    storageBucket: 'compactmeter-1ec77.firebasestorage.app',
    iosBundleId: 'com.example.appCompactmeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA24oWqCR85FObPInV-bcDEhEWDV7J1e80',
    appId: '1:132422513872:ios:dfe8804d53faaf6a419ad5',
    messagingSenderId: '132422513872',
    projectId: 'compactmeter-1ec77',
    storageBucket: 'compactmeter-1ec77.firebasestorage.app',
    iosBundleId: 'com.example.appCompactmeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0VlbCBzqg976QDq-vpoh3YmzTOro-guU',
    appId: '1:132422513872:web:4d11bdf247d6ddc3419ad5',
    messagingSenderId: '132422513872',
    projectId: 'compactmeter-1ec77',
    authDomain: 'compactmeter-1ec77.firebaseapp.com',
    storageBucket: 'compactmeter-1ec77.firebasestorage.app',
  );
}
